### ISSUE TITLE
Update release to semver format

### ISSUE THREAD

**Issue by audreydcv** [yasarix/workergo#1]
Latest release is v2, but go mod requires semver format. https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning

**Comment by yasarix** [comment]
Please add `gopkg.in/yasarix/workergo.v2 v2.1.1` to your `go.mod` and import `gopkg.in/yasarix/workergo.v2`

**Comment by yasarix** [comment]
Issue is fixed with 2.1.1

**Comment by audreydcv** [comment]
Thank you!
